name: Deploy master branch to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    # Check out repository
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Fetch Complete Repository History
      run: git fetch --prune --tags --unshallow
    # Installs node v12
    - name: Use Node.js Version 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Create Test Database
      run: psql "postgres://postgres:postgres@localhost:5432" -c 'create database "test-database";'
    - name: Install Node Modules
      run: npm install
    - name: Test
      run: npm test
      env:
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/test-database"
    - run: git config --global user.email "no-reply@example.org"
    - run: git config --global user.name "Github Actions Deploy Script"
    - name: Build and Deploy to Heroku
      run: npm run deploy
      env:
        HEROKU_APP_NAME: blooming-reaches-38374
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
