name: Run Tests For Pull Requests
on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    # Job name is Greeting
    name: NPM Test
    # This job runs on Linux
    runs-on: ubuntu-latest

    #  NEeded services
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    # Check out repository
    - name: Clone Source Code
      uses: actions/checkout@v2

    - name: Use Node.js Version 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Create Test Database
      run: psql "postgres://postgres:postgres@localhost:5432" -c 'create database "test-database";'

    - name: Install NPM Modules
      run: npm install

    - name: Build Webpack Bundle
      run: npm run build-client

    - name: Tests
      run: npm test
      env:
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/test-database"

    - name: Linter
      run: npm run lint
